---
title: "4. Tune model parameters"
author: "Yao Yu"
date: "5/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Get Started with tidymodels guide:
# https://www.tidymodels.org/start/models/

# Main packages
# Needed for parsnip package and tidymodels
library(tidymodels)
library(tidyverse)

# Helper packages
# Needed for cells data
library(modeldata)
# Needed for varaible importance plots
library(vip)
```

```{r data}
# Loading in the data
data(cells, package = "modeldata")

# Splitting our data
set.seed(121)
cell_split <- initial_split(cells %>% select(-case), strata = class)
cell_train <- training(cell_split)
cell_test <- testing(cell_split)
```

```{r tuning hyperparameters}
# Decision Tree Model with Tune specifications
tune_spec <- decision_tree(cost_complexity = tune(),
                           tree_depth = tune()) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

# Creating a regular grid of values to test tuning
tree_grid <- grid_regular(cost_complexity(),
                          tree_depth(),
                          levels = 5)

# Creating CV folds
set.seed(121)
cell_folds <- vfold_cv(cell_train)
```

```{r model tuning with grid}
set.seed(121)

# Creating a workflow
tree_wf <- workflow() %>% 
  add_model(tune_spec) %>% 
  add_formula(class ~ .)

# Tuning the workflow with grid
tree_res <- tree_wf %>% 
  tune_grid(resamples = cell_folds,
            grid = tree_grid)

# Collecting the metrics
tree_res %>% 
  collect_metrics()

# Plotting the metrics
tree_res %>% 
  collect_metrics() %>% 
  mutate(tree_depth = factor(tree_depth)) %>% 
  ggplot(aes(x = cost_complexity, y = mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "plasma", begin = 0.9, end = 0) +
  theme_linedraw()

# Showing the top 5 best metrics
tree_res %>% 
  show_best("roc_auc")

# Selecting the best hyperparametere values
best_tree <- tree_res %>% 
  select_best("roc_auc")

best_tree
```

```{r final model}
# Creating our final model with the best hyperparameters
final_wf <- tree_wf %>% 
  finalize_workflow(best_tree)

# Fitting our final decision tree
final_tree <- final_wf %>% 
  fit(data = cell_train)

# Estimating variable importance
final_tree %>% 
  pull_workflow_fit() %>% 
  vip()
```

```{r last fit}
# Estimating our final fit with our new data
final_fit <- final_wf %>% 
  last_fit(cell_split)

# Looking at our final metrics
final_fit %>% 
  collect_metrics()

# Plotting an ROC Curve
final_fit %>% 
  collect_predictions() %>% 
  roc_curve(class, .pred_PS) %>% 
  autoplot()
```








